


version: "3.9"

services:

  db:
    image: postgres
    env_file:
      - ./.env.dev
    volumes:
      - ./data/db:/var/lib/postgresql/data
    
  web:
    build: .
    command: bash -c "python manage.py migrate && python3 manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    container_name: seedtest
    volumes:
      - .:/seedtest
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A seedtest worker -l info
    volumes:
      - ./seedtest/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - web
      - db

  celery-beat:
    build: .
    command: celery -A seedtest beat -l info
    volumes:
      - ./seedtest/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - web
      - db
