# Generated by Django 4.0.1 on 2022-02-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_items_title_alter_items_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='kids',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
