# Generated by Django 4.0.1 on 2022-02-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_items_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='kids',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
