# Generated by Django 4.0.1 on 2022-02-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_items_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='order_frm',
            field=models.CharField(blank=True, default='earlier', max_length=200, null=True),
        ),
    ]
