# Generated by Django 4.0.1 on 2022-02-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_items_order_frm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['-id']},
        ),
    ]
